//下面的标志用于文件排序,请不要删除
//#CMDIndex= 50

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: CommPro.proto

package protomsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//空消息共用
type NullMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullMsg) Reset() {
	*x = NullMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommPro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullMsg) ProtoMessage() {}

func (x *NullMsg) ProtoReflect() protoreflect.Message {
	mi := &file_CommPro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullMsg.ProtoReflect.Descriptor instead.
func (*NullMsg) Descriptor() ([]byte, []int) {
	return file_CommPro_proto_rawDescGZIP(), []int{0}
}

//结果码
type RestInt32CodeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestCode int32 `protobuf:"varint,1,opt,name=rest_code,json=restCode,proto3" json:"rest_code,omitempty"`
}

func (x *RestInt32CodeMsg) Reset() {
	*x = RestInt32CodeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommPro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestInt32CodeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestInt32CodeMsg) ProtoMessage() {}

func (x *RestInt32CodeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_CommPro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestInt32CodeMsg.ProtoReflect.Descriptor instead.
func (*RestInt32CodeMsg) Descriptor() ([]byte, []int) {
	return file_CommPro_proto_rawDescGZIP(), []int{1}
}

func (x *RestInt32CodeMsg) GetRestCode() int32 {
	if x != nil {
		return x.RestCode
	}
	return 0
}

type ServerInfoPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId        int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppKind      int32  `protobuf:"varint,2,opt,name=app_kind,json=appKind,proto3" json:"app_kind,omitempty"`
	AppName      string `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Addr         string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`  //给客户端的连接地址
	Port         int32  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"` //给客户端的连接端口
	Group        int32  `protobuf:"varint,6,opt,name=group,proto3" json:"group,omitempty"`
	ServerStatus int32  `protobuf:"varint,7,opt,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty"`
	Num          int32  `protobuf:"varint,8,opt,name=num,proto3" json:"num,omitempty"` //服务器数量
}

func (x *ServerInfoPb) Reset() {
	*x = ServerInfoPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommPro_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoPb) ProtoMessage() {}

func (x *ServerInfoPb) ProtoReflect() protoreflect.Message {
	mi := &file_CommPro_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoPb.ProtoReflect.Descriptor instead.
func (*ServerInfoPb) Descriptor() ([]byte, []int) {
	return file_CommPro_proto_rawDescGZIP(), []int{2}
}

func (x *ServerInfoPb) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ServerInfoPb) GetAppKind() int32 {
	if x != nil {
		return x.AppKind
	}
	return 0
}

func (x *ServerInfoPb) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ServerInfoPb) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServerInfoPb) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerInfoPb) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *ServerInfoPb) GetServerStatus() int32 {
	if x != nil {
		return x.ServerStatus
	}
	return 0
}

func (x *ServerInfoPb) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

//返回的消息体这个消息体可扩展,在收消息接口统一处理，这样就不用修改单个命令处理函数的参数
//服务器返回消息给客户端
type MsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResCode uint32 `protobuf:"varint,1,opt,name=res_code,json=resCode,proto3" json:"res_code,omitempty"` //返回的消息码
	PbMsg   []byte `protobuf:"bytes,2,opt,name=pb_msg,json=pbMsg,proto3" json:"pb_msg,omitempty"`        //具体的消息
}

func (x *MsgRes) Reset() {
	*x = MsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommPro_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRes) ProtoMessage() {}

func (x *MsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_CommPro_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRes.ProtoReflect.Descriptor instead.
func (*MsgRes) Descriptor() ([]byte, []int) {
	return file_CommPro_proto_rawDescGZIP(), []int{3}
}

func (x *MsgRes) GetResCode() uint32 {
	if x != nil {
		return x.ResCode
	}
	return 0
}

func (x *MsgRes) GetPbMsg() []byte {
	if x != nil {
		return x.PbMsg
	}
	return nil
}

//客户端消息到网关后消息转发到其他服务器消息体
type MsgTransReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromConId uint32 `protobuf:"varint,1,opt,name=from_con_id,json=fromConId,proto3" json:"from_con_id,omitempty"` //每一层的连接id
	MainCmd   uint32 `protobuf:"varint,2,opt,name=main_cmd,json=mainCmd,proto3" json:"main_cmd,omitempty"`         //转发的命令
	PbMsg     []byte `protobuf:"bytes,3,opt,name=pb_msg,json=pbMsg,proto3" json:"pb_msg,omitempty"`                //具体的消息
}

func (x *MsgTransReq) Reset() {
	*x = MsgTransReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommPro_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgTransReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransReq) ProtoMessage() {}

func (x *MsgTransReq) ProtoReflect() protoreflect.Message {
	mi := &file_CommPro_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransReq.ProtoReflect.Descriptor instead.
func (*MsgTransReq) Descriptor() ([]byte, []int) {
	return file_CommPro_proto_rawDescGZIP(), []int{4}
}

func (x *MsgTransReq) GetFromConId() uint32 {
	if x != nil {
		return x.FromConId
	}
	return 0
}

func (x *MsgTransReq) GetMainCmd() uint32 {
	if x != nil {
		return x.MainCmd
	}
	return 0
}

func (x *MsgTransReq) GetPbMsg() []byte {
	if x != nil {
		return x.PbMsg
	}
	return nil
}

//消息回复找对应的服务器,对应多各客户端
type MsgTransRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendTo      []uint32 `protobuf:"varint,1,rep,packed,name=send_to,json=sendTo,proto3" json:"send_to,omitempty"`          //返回给哪些客户端
	MainCmd     uint32   `protobuf:"varint,2,opt,name=main_cmd,json=mainCmd,proto3" json:"main_cmd,omitempty"`              //转发的命令
	ToClientMsg *MsgRes  `protobuf:"bytes,3,opt,name=to_client_msg,json=toClientMsg,proto3" json:"to_client_msg,omitempty"` //给客户端返回消息
}

func (x *MsgTransRes) Reset() {
	*x = MsgTransRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommPro_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgTransRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransRes) ProtoMessage() {}

func (x *MsgTransRes) ProtoReflect() protoreflect.Message {
	mi := &file_CommPro_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransRes.ProtoReflect.Descriptor instead.
func (*MsgTransRes) Descriptor() ([]byte, []int) {
	return file_CommPro_proto_rawDescGZIP(), []int{5}
}

func (x *MsgTransRes) GetSendTo() []uint32 {
	if x != nil {
		return x.SendTo
	}
	return nil
}

func (x *MsgTransRes) GetMainCmd() uint32 {
	if x != nil {
		return x.MainCmd
	}
	return 0
}

func (x *MsgTransRes) GetToClientMsg() *MsgRes {
	if x != nil {
		return x.ToClientMsg
	}
	return nil
}

var File_CommPro_proto protoreflect.FileDescriptor

var file_CommPro_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x50, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x50, 0x72, 0x6f, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x75, 0x6c, 0x6c,
	0x4d, 0x73, 0x67, 0x22, 0x2f, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x43, 0x6f, 0x64, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0xd0, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x50, 0x62, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x70, 0x70, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x3a, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x62,
	0x4d, 0x73, 0x67, 0x22, 0x5f, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70,
	0x62, 0x4d, 0x73, 0x67, 0x22, 0x76, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x12, 0x33, 0x0a, 0x0d, 0x74, 0x6f, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x50, 0x72, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x52,
	0x0b, 0x74, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_CommPro_proto_rawDescOnce sync.Once
	file_CommPro_proto_rawDescData = file_CommPro_proto_rawDesc
)

func file_CommPro_proto_rawDescGZIP() []byte {
	file_CommPro_proto_rawDescOnce.Do(func() {
		file_CommPro_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommPro_proto_rawDescData)
	})
	return file_CommPro_proto_rawDescData
}

var file_CommPro_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_CommPro_proto_goTypes = []interface{}{
	(*NullMsg)(nil),          // 0: CommPro.NullMsg
	(*RestInt32CodeMsg)(nil), // 1: CommPro.RestInt32CodeMsg
	(*ServerInfoPb)(nil),     // 2: CommPro.ServerInfoPb
	(*MsgRes)(nil),           // 3: CommPro.MsgRes
	(*MsgTransReq)(nil),      // 4: CommPro.MsgTransReq
	(*MsgTransRes)(nil),      // 5: CommPro.MsgTransRes
}
var file_CommPro_proto_depIdxs = []int32{
	3, // 0: CommPro.MsgTransRes.to_client_msg:type_name -> CommPro.MsgRes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommPro_proto_init() }
func file_CommPro_proto_init() {
	if File_CommPro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommPro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommPro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestInt32CodeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommPro_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommPro_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommPro_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgTransReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommPro_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgTransRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommPro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommPro_proto_goTypes,
		DependencyIndexes: file_CommPro_proto_depIdxs,
		MessageInfos:      file_CommPro_proto_msgTypes,
	}.Build()
	File_CommPro_proto = out.File
	file_CommPro_proto_rawDesc = nil
	file_CommPro_proto_goTypes = nil
	file_CommPro_proto_depIdxs = nil
}
