//下面的标志用于文件排序,请不要删除
//#CMDIndex= 500

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: Login.proto

package protomsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//连接登录服成功后发送确认
type C2L_LoginConnectAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *C2L_LoginConnectAck) Reset() {
	*x = C2L_LoginConnectAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_LoginConnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_LoginConnectAck) ProtoMessage() {}

func (x *C2L_LoginConnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_LoginConnectAck.ProtoReflect.Descriptor instead.
func (*C2L_LoginConnectAck) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{0}
}

func (x *C2L_LoginConnectAck) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

//连接登录服成功后登录服回复
type L2C_LoginConnectAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixNano int64 `protobuf:"varint,1,opt,name=UnixNano,proto3" json:"UnixNano,omitempty"` //同步时间
}

func (x *L2C_LoginConnectAck) Reset() {
	*x = L2C_LoginConnectAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_LoginConnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_LoginConnectAck) ProtoMessage() {}

func (x *L2C_LoginConnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_LoginConnectAck.ProtoReflect.Descriptor instead.
func (*L2C_LoginConnectAck) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{1}
}

func (x *L2C_LoginConnectAck) GetUnixNano() int64 {
	if x != nil {
		return x.UnixNano
	}
	return 0
}

//登陆
type C2L_LoginMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc string `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"` //账号
}

func (x *C2L_LoginMsg) Reset() {
	*x = C2L_LoginMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_LoginMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_LoginMsg) ProtoMessage() {}

func (x *C2L_LoginMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_LoginMsg.ProtoReflect.Descriptor instead.
func (*C2L_LoginMsg) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{2}
}

func (x *C2L_LoginMsg) GetAcc() string {
	if x != nil {
		return x.Acc
	}
	return ""
}

//登录返回角色
type L2C_LoginMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID   int64  `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`    //账号id
	RoomID   int32  `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`    //账号id
	RoleName string `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName,omitempty"` //角色名
}

func (x *L2C_LoginMsg) Reset() {
	*x = L2C_LoginMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_LoginMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_LoginMsg) ProtoMessage() {}

func (x *L2C_LoginMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_LoginMsg.ProtoReflect.Descriptor instead.
func (*L2C_LoginMsg) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{3}
}

func (x *L2C_LoginMsg) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *L2C_LoginMsg) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *L2C_LoginMsg) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

//创建角色
type C2L_CreateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` //用户
}

func (x *C2L_CreateRoleReq) Reset() {
	*x = C2L_CreateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_CreateRoleReq) ProtoMessage() {}

func (x *C2L_CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_CreateRoleReq.ProtoReflect.Descriptor instead.
func (*C2L_CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{4}
}

func (x *C2L_CreateRoleReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

//返回创建的角色id与房间号
type L2C_CreateRoleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID   int64  `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`    //账号id
	RoomID   int32  `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`    //账号id
	RoleName string `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName,omitempty"` //角色名
}

func (x *L2C_CreateRoleRes) Reset() {
	*x = L2C_CreateRoleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_CreateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_CreateRoleRes) ProtoMessage() {}

func (x *L2C_CreateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_CreateRoleRes.ProtoReflect.Descriptor instead.
func (*L2C_CreateRoleRes) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{5}
}

func (x *L2C_CreateRoleRes) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *L2C_CreateRoleRes) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *L2C_CreateRoleRes) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

var File_Login_proto protoreflect.FileDescriptor

var file_Login_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x32, 0x4c, 0x5f, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x31, 0x0a, 0x13, 0x4c, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61,
	0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61,
	0x6e, 0x6f, 0x22, 0x20, 0x0a, 0x0c, 0x43, 0x32, 0x4c, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d,
	0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x63, 0x63, 0x22, 0x5a, 0x0a, 0x0c, 0x4c, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x2f, 0x0a, 0x11, 0x43, 0x32, 0x4c, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x5f, 0x0a, 0x11, 0x4c, 0x32, 0x43, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Login_proto_rawDescOnce sync.Once
	file_Login_proto_rawDescData = file_Login_proto_rawDesc
)

func file_Login_proto_rawDescGZIP() []byte {
	file_Login_proto_rawDescOnce.Do(func() {
		file_Login_proto_rawDescData = protoimpl.X.CompressGZIP(file_Login_proto_rawDescData)
	})
	return file_Login_proto_rawDescData
}

var file_Login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Login_proto_goTypes = []interface{}{
	(*C2L_LoginConnectAck)(nil), // 0: Login.C2L_LoginConnectAck
	(*L2C_LoginConnectAck)(nil), // 1: Login.L2C_LoginConnectAck
	(*C2L_LoginMsg)(nil),        // 2: Login.C2L_LoginMsg
	(*L2C_LoginMsg)(nil),        // 3: Login.L2C_LoginMsg
	(*C2L_CreateRoleReq)(nil),   // 4: Login.C2L_CreateRoleReq
	(*L2C_CreateRoleRes)(nil),   // 5: Login.L2C_CreateRoleRes
}
var file_Login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Login_proto_init() }
func file_Login_proto_init() {
	if File_Login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_LoginConnectAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_LoginConnectAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_LoginMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_LoginMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_CreateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_CreateRoleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Login_proto_goTypes,
		DependencyIndexes: file_Login_proto_depIdxs,
		MessageInfos:      file_Login_proto_msgTypes,
	}.Build()
	File_Login_proto = out.File
	file_Login_proto_rawDesc = nil
	file_Login_proto_goTypes = nil
	file_Login_proto_depIdxs = nil
}
