//下面的标志用于文件排序,请不要删除
//#CMDIndex= 600

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: MsgPro.proto

package protomsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//发送消息
type C2L_SendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conent string `protobuf:"bytes,1,opt,name=conent,proto3" json:"conent,omitempty"`  //发送消息
	RoomID int32  `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"` //房间id
}

func (x *C2L_SendMsgReq) Reset() {
	*x = C2L_SendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_SendMsgReq) ProtoMessage() {}

func (x *C2L_SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_SendMsgReq.ProtoReflect.Descriptor instead.
func (*C2L_SendMsgReq) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{0}
}

func (x *C2L_SendMsgReq) GetConent() string {
	if x != nil {
		return x.Conent
	}
	return ""
}

func (x *C2L_SendMsgReq) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type MsgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conent   string `protobuf:"bytes,1,opt,name=conent,proto3" json:"conent,omitempty"`      //发送消息
	RoleName string `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`  //角色名
	RoomID   int32  `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`     //房间id
	SendTime int64  `protobuf:"varint,4,opt,name=sendTime,proto3" json:"sendTime,omitempty"` //发送时间
}

func (x *MsgInfo) Reset() {
	*x = MsgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInfo) ProtoMessage() {}

func (x *MsgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInfo.ProtoReflect.Descriptor instead.
func (*MsgInfo) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{1}
}

func (x *MsgInfo) GetConent() string {
	if x != nil {
		return x.Conent
	}
	return ""
}

func (x *MsgInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *MsgInfo) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *MsgInfo) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

//发送消息
type L2C_SendMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgInfo *MsgInfo `protobuf:"bytes,1,opt,name=msgInfo,proto3" json:"msgInfo,omitempty"` //发送消息
}

func (x *L2C_SendMsgRes) Reset() {
	*x = L2C_SendMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_SendMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_SendMsgRes) ProtoMessage() {}

func (x *L2C_SendMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_SendMsgRes.ProtoReflect.Descriptor instead.
func (*L2C_SendMsgRes) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{2}
}

func (x *L2C_SendMsgRes) GetMsgInfo() *MsgInfo {
	if x != nil {
		return x.MsgInfo
	}
	return nil
}

//获取消息列表
type C2L_GetRoomMsgListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"` //房间id
}

func (x *C2L_GetRoomMsgListReq) Reset() {
	*x = C2L_GetRoomMsgListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_GetRoomMsgListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_GetRoomMsgListReq) ProtoMessage() {}

func (x *C2L_GetRoomMsgListReq) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_GetRoomMsgListReq.ProtoReflect.Descriptor instead.
func (*C2L_GetRoomMsgListReq) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{3}
}

func (x *C2L_GetRoomMsgListReq) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

//获取消息列表回复
type L2C_GetRoomMsgListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32      `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"` //房间id
	Msgs   []*MsgInfo `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`      //消息列表
}

func (x *L2C_GetRoomMsgListRes) Reset() {
	*x = L2C_GetRoomMsgListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_GetRoomMsgListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_GetRoomMsgListRes) ProtoMessage() {}

func (x *L2C_GetRoomMsgListRes) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_GetRoomMsgListRes.ProtoReflect.Descriptor instead.
func (*L2C_GetRoomMsgListRes) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{4}
}

func (x *L2C_GetRoomMsgListRes) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *L2C_GetRoomMsgListRes) GetMsgs() []*MsgInfo {
	if x != nil {
		return x.Msgs
	}
	return nil
}

//获取玩家信息
type C2L_GetRoleInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string `protobuf:"bytes,1,opt,name=roleName,proto3" json:"roleName,omitempty"` //发送消息
}

func (x *C2L_GetRoleInfoReq) Reset() {
	*x = C2L_GetRoleInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_GetRoleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_GetRoleInfoReq) ProtoMessage() {}

func (x *C2L_GetRoleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_GetRoleInfoReq.ProtoReflect.Descriptor instead.
func (*C2L_GetRoleInfoReq) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{5}
}

func (x *C2L_GetRoleInfoReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

//获取玩家信息回复
type L2C_GetUserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName   string `protobuf:"bytes,1,opt,name=roleName,proto3" json:"roleName,omitempty"`      //发送消息
	LoginTime  int64  `protobuf:"varint,2,opt,name=loginTime,proto3" json:"loginTime,omitempty"`   //发送消息
	OnlineTime int64  `protobuf:"varint,3,opt,name=onlineTime,proto3" json:"onlineTime,omitempty"` //发送消息
	RoomID     int32  `protobuf:"varint,4,opt,name=roomID,proto3" json:"roomID,omitempty"`         //房间id
}

func (x *L2C_GetUserInfoRes) Reset() {
	*x = L2C_GetUserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_GetUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_GetUserInfoRes) ProtoMessage() {}

func (x *L2C_GetUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_GetUserInfoRes.ProtoReflect.Descriptor instead.
func (*L2C_GetUserInfoRes) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{6}
}

func (x *L2C_GetUserInfoRes) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *L2C_GetUserInfoRes) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *L2C_GetUserInfoRes) GetOnlineTime() int64 {
	if x != nil {
		return x.OnlineTime
	}
	return 0
}

func (x *L2C_GetUserInfoRes) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

//获取最近10分钟发送最频繁的消息
type C2L_PopularMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"` //房间id
}

func (x *C2L_PopularMsgReq) Reset() {
	*x = C2L_PopularMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_PopularMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_PopularMsgReq) ProtoMessage() {}

func (x *C2L_PopularMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_PopularMsgReq.ProtoReflect.Descriptor instead.
func (*C2L_PopularMsgReq) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{7}
}

func (x *C2L_PopularMsgReq) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type L2C_PopularMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PopMsg []string `protobuf:"bytes,1,rep,name=popMsg,proto3" json:"popMsg,omitempty"` //房间id
}

func (x *L2C_PopularMsgRes) Reset() {
	*x = L2C_PopularMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_PopularMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_PopularMsgRes) ProtoMessage() {}

func (x *L2C_PopularMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_PopularMsgRes.ProtoReflect.Descriptor instead.
func (*L2C_PopularMsgRes) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{8}
}

func (x *L2C_PopularMsgRes) GetPopMsg() []string {
	if x != nil {
		return x.PopMsg
	}
	return nil
}

//切换房间
type C2L_SwitchRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"` //房间id
}

func (x *C2L_SwitchRoomReq) Reset() {
	*x = C2L_SwitchRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2L_SwitchRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2L_SwitchRoomReq) ProtoMessage() {}

func (x *C2L_SwitchRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2L_SwitchRoomReq.ProtoReflect.Descriptor instead.
func (*C2L_SwitchRoomReq) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{9}
}

func (x *C2L_SwitchRoomReq) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

//切换房间回复
type L2C_SwitchRoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int32      `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"` //房间id
	Msgs   []*MsgInfo `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`      //消息列表
}

func (x *L2C_SwitchRoomRes) Reset() {
	*x = L2C_SwitchRoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MsgPro_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2C_SwitchRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2C_SwitchRoomRes) ProtoMessage() {}

func (x *L2C_SwitchRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_MsgPro_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2C_SwitchRoomRes.ProtoReflect.Descriptor instead.
func (*L2C_SwitchRoomRes) Descriptor() ([]byte, []int) {
	return file_MsgPro_proto_rawDescGZIP(), []int{10}
}

func (x *L2C_SwitchRoomRes) GetRoomID() int32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *L2C_SwitchRoomRes) GetMsgs() []*MsgInfo {
	if x != nil {
		return x.Msgs
	}
	return nil
}

var File_MsgPro_proto protoreflect.FileDescriptor

var file_MsgPro_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x50, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x4d, 0x73, 0x67, 0x50, 0x72, 0x6f, 0x22, 0x40, 0x0a, 0x0e, 0x43, 0x32, 0x4c, 0x5f, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x71, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x0e, 0x4c,
	0x32, 0x43, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a,
	0x07, 0x6d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x4d, 0x73, 0x67, 0x50, 0x72, 0x6f, 0x2e, 0x6d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x32, 0x4c, 0x5f,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x54, 0x0a, 0x15, 0x4c, 0x32, 0x43,
	0x5f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x73,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x72,
	0x6f, 0x2e, 0x6d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22,
	0x30, 0x0a, 0x12, 0x43, 0x32, 0x4c, 0x5f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x4c, 0x32, 0x43, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x11, 0x43, 0x32,
	0x4c, 0x5f, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x11, 0x4c, 0x32, 0x43, 0x5f, 0x50,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6f, 0x70, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f,
	0x70, 0x4d, 0x73, 0x67, 0x22, 0x2b, 0x0a, 0x11, 0x43, 0x32, 0x4c, 0x5f, 0x53, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x22, 0x50, 0x0a, 0x11, 0x4c, 0x32, 0x43, 0x5f, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x23,
	0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4d,
	0x73, 0x67, 0x50, 0x72, 0x6f, 0x2e, 0x6d, 0x73, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6d,
	0x73, 0x67, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MsgPro_proto_rawDescOnce sync.Once
	file_MsgPro_proto_rawDescData = file_MsgPro_proto_rawDesc
)

func file_MsgPro_proto_rawDescGZIP() []byte {
	file_MsgPro_proto_rawDescOnce.Do(func() {
		file_MsgPro_proto_rawDescData = protoimpl.X.CompressGZIP(file_MsgPro_proto_rawDescData)
	})
	return file_MsgPro_proto_rawDescData
}

var file_MsgPro_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_MsgPro_proto_goTypes = []interface{}{
	(*C2L_SendMsgReq)(nil),        // 0: MsgPro.C2L_SendMsgReq
	(*MsgInfo)(nil),               // 1: MsgPro.msgInfo
	(*L2C_SendMsgRes)(nil),        // 2: MsgPro.L2C_SendMsgRes
	(*C2L_GetRoomMsgListReq)(nil), // 3: MsgPro.C2L_GetRoomMsgListReq
	(*L2C_GetRoomMsgListRes)(nil), // 4: MsgPro.L2C_GetRoomMsgListRes
	(*C2L_GetRoleInfoReq)(nil),    // 5: MsgPro.C2L_GetRoleInfoReq
	(*L2C_GetUserInfoRes)(nil),    // 6: MsgPro.L2C_GetUserInfoRes
	(*C2L_PopularMsgReq)(nil),     // 7: MsgPro.C2L_PopularMsgReq
	(*L2C_PopularMsgRes)(nil),     // 8: MsgPro.L2C_PopularMsgRes
	(*C2L_SwitchRoomReq)(nil),     // 9: MsgPro.C2L_SwitchRoomReq
	(*L2C_SwitchRoomRes)(nil),     // 10: MsgPro.L2C_SwitchRoomRes
}
var file_MsgPro_proto_depIdxs = []int32{
	1, // 0: MsgPro.L2C_SendMsgRes.msgInfo:type_name -> MsgPro.msgInfo
	1, // 1: MsgPro.L2C_GetRoomMsgListRes.msgs:type_name -> MsgPro.msgInfo
	1, // 2: MsgPro.L2C_SwitchRoomRes.msgs:type_name -> MsgPro.msgInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_MsgPro_proto_init() }
func file_MsgPro_proto_init() {
	if File_MsgPro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MsgPro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_SendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_SendMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_GetRoomMsgListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_GetRoomMsgListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_GetRoleInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_GetUserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_PopularMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_PopularMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2L_SwitchRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MsgPro_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2C_SwitchRoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MsgPro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MsgPro_proto_goTypes,
		DependencyIndexes: file_MsgPro_proto_depIdxs,
		MessageInfos:      file_MsgPro_proto_msgTypes,
	}.Build()
	File_MsgPro_proto = out.File
	file_MsgPro_proto_rawDesc = nil
	file_MsgPro_proto_goTypes = nil
	file_MsgPro_proto_depIdxs = nil
}
